### ISSUE TITLE
Unable to find limit

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#121]
Happy New Year!

This doesn't work: `limit((1+\a/x)^x,infinity)`.

P.S. Actually, it's just another manifestation of #104.

**Comment by hanna-kn** [comment]
Fixed. It's not really related to #104, but a result of an overly cautious handling of infinity in the rather primitive limit function (it can doubtless be improved further).

**Comment by vvs-** [comment]
I meant, that if there existed more generic framework then it could try different strategies to find that the above expression can be reduced to `(1+1/x)^x`. Using some specific transformation works in simple cases but it's not generic enough to improve on a broad case, e.g. it's still failed in `limit((1+\a/x)^(x/\a),infinity)` which is essentially the same. And besides, specific heuristics presently require modification of core library, that;s not appealing to non-programmers.

**Comment by vvs-** [comment]
> (how do you mean that (1+\a/x)^x can be reduced to (1+1/x)^x

`((1+\a/x)^(x/\a))^\a=(1+\a/x)^x`, but `(1+\a/x)^(x/\a)=(1+1/y)^y` where `y=x/\a`.

**Comment by vvs-** [comment]
BTW, even `limit((1+|\a/x|)^(|x/\a|), infinity)` failed unless unknowns>0. And there is a typo in qalculate-gtk's callbacks.cc in line 1678 which prevents it from successful compilation.

**Comment by hanna-kn** [comment]
The x variable is replaced by a temporary positive variable in the limit function (a similar solution is used in other functions, where the unknown variable can in addition be associated with a specific interval). The reason the limit fails is because _a_ might be zero (which you should see if you only changes the assumptions of the specific variable).

> And there is a typo in qalculate-gtk's callbacks.cc in line 1678 which prevents it from successful compilation.

Fixed.

**Comment by vvs-** [comment]
> The reason the limit fails is because a might be zero (which you should see if you only change the assumptions of the specific variable).

I don't see where I could change assumptions for _a_ and if I change global assumptions for unknowns to _non_zero_ the limit still fails. Only when I change it to _positive_ it succeeds.

**Comment by hanna-kn** [comment]
> I don't see where I could change assumptions for _a_ and if I change global assumptions for unknowns to _non_zero_ the limit still fails. Only when I change it to _positive_ it succeeds.

It also succeeds with negative assumptions. For some reason the limit function needs to know if _a_ is negative or positive (and that it isn't zero). I do not yet known why, but you should generally only expect the limit function to handle relatively simple expressions.

You can change the assumptions of _x_ or use _y_ instead of _a_ and change the assumptions of _y_.

**Comment by vvs-** [comment]
> For some reason the limit function needs to know if a is negative or positive (and that it isn't zero). I do not yet known why

Aren't these heuristics just craving to be ported from C++? I know, this is below the belt. I'm sorry and, please, don't feel offended by my sincere remarks.
